const quotes = [
    'Wubba-lubba-dub-dub!',
    'Rikki-Tikki-Tavi, biatch!',
    'Oh, shit!',
    'I can\'t really get tired of this',
    'They call me Mister Tibbs',
    'I drink your milkshake!',
    'Chewie, we\'re home',
    'I\'m walking here!',
    'It was Beauty killed the Beast.',
    'They\'re here!',
    'Elementary, my dear Watson.',
    'It\'s alive! It\'s alive!',
    'Pay no attention to that man behind the curtain!',
    'I\'m having an old friend for dinner.',
    'I\'m not bad. I\'m just drawn that way.',
    'Shaken, not stirred.',
    'Roads? Where we\'re going we don\'t need roads.',
    'Show me the money!',
    'Carpe diem. Seize the day, boys.',
    'To infinity and beyond!',
    'Why so serious?',
    'How is this a fair trial? Our laywer is a Morty.'];

export default quotes;